sonar.projectKey=kmartin-ops
sonar.organization=Kmartin-ops

# Project info
sonar.projectName=CollabHub
sonar.projectVersion=0.4

# Source
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

# Coverage report
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclusions — same as local SonarQube
sonar.coverage.exclusions=\
    **/dto/**,\
    **/mapper/**,\
    **/config/**,\
    **/domain/**,\
    **/exception/**,\
    **/controller/**,\
    **/report/**,\
    **/security/**,\
    **/*Application.java,\
    **/StartupRunner.java,\
    **/notification/**,\
    **/async/**

sonar.cpd.exclusions=\
    **/dto/**,\
    **/domain/**
