spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true    # show SQL queries in dev

logging:
  level:
    com.collabhub: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG